project:
  type: website

website:
  title: "Hui's Visual Analytics"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "In-class Exercises"
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
    right: 
      - href: index.qmd
        text: Home
format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

